### ISSUE TITLE
Geospatial Metrics Dimensionality

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#118]
I'm working on the quick and dirty "summarize my layers in the map" feature.

@joewheaton what is the "outer dimension" that folks will want to review the results? Is it by mask polygon or by layer?

1. For each polygon list all the measurements by layer
2. For each layer list the measurements by polygon

**Comment by joewheaton** [comment]
I'm not sure I understand what you are asking? So this is not a single layer Zonal Statistics feature with inputs of a feature class (i.e. point, polyline, polygon) and the summary of it? I think that would be most useful. Remember #43?

Is this feature your talking about choose a DCE, and basically calculate all the metrics it can? In other words, it does what we're doing in analysis, but doesn't save it to the database and it is just a 1 column analysis (rows are the different things it can calculate)? Or is that what you're asking?  Maybe it is user choice? I guess another way of asking this is 1) is like an AOI that is full extents, and 2) is classic mask and you summarize by polygons of like classes? I am still a little unclear on what exactly are the value**s** that get calculated? Are you thinking these are based on the attribute field(s) in the layer(s), or based on their geometry? Obviously, a zonal statistic is the later. 

Another thing confusing me on calculation of all statistics, is whether or not we need a "statistics object". With a measurement or metric, we dome down to one value or statistic. But for all these things where we are summarizing or sampling multiple values (whether those are rows representing features, or from intersecting geometry) the actual object is a distribution (i.e. a histogram) and then all your standard statistics are possible off that. But at that point, how is what we're doing any different than the [Statistics Panel](https://docs.qgis.org/3.22/en/docs/training_manual/vector_analysis/spatial_statistics.html#basic-fa-basic-statistics)?
![image](https://user-images.githubusercontent.com/9723905/192784171-65179429-a209-47aa-b03b-a6a289712c86.png)

Now a lot of our users may not know how to use the Statistics Panel, so letting them do something (i.e. make a selection or a definition query) and then setting that up for them and returning display in (and turning on if off) the Statistics panel, could be useful. Here, you are teaching them how to get answers with vanilla QGIS. However, even if this isn't what you mean, it is important to recognize that every single cell (or maybe row) in this metric table essentially has statistics behind it, hence the dimensionality. We don't need to store that, because Q can summarize and calculate all that on the fly. 

Anyhow, I am going around in circles. I just don't know what you're asking precisely. Sorry.

Regardless, I'm not sure what it is best to call this feature. Lets discuss.
