### ISSUE TITLE
Add a `Project` menu like we had in GCD to toolbar (or to panel)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#131]
In GCD, we had a project menu:
![image](https://user-images.githubusercontent.com/9723905/196517210-52e4c2db-ccb8-4505-a76f-695a9fc2d6f9.png)

I think we should do the same thing in QRiS. We then put the following commands
- [ ] `New QRiS Project`
- [ ] `Open QRiS Project`
- [ ] `Recent QRiS Projects` - _I really like this for making it easier for user to find recent work._
- [ ] `Close QRiS Project and Map` - #130 
- [ ] `Project Properties` - _same as `Edit Properties`
- [ ] `Browse QRiS Project Folder`

**Comment by philipbaileynar** [comment]
The project menu is implemented in 0.1.6-alpha.

I have left the "properties", "browse to folder" off because, semantically, the toolbar merely controls which project is open. Operations on the project itself take place inside the QRiS project explorer. (I broke my own rule by adding the Close project menu to the toolbar, but it's not currently hooked up.)
