### ISSUE TITLE
Redesign Data Capture Event Form

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#149]
I know @joewheaton  doesn't like the current protocols list, so we are going to move to a tree making visible all the layers available in QRiS. Here's my suggestion for how we could organize them:

- alphabetical (essentially a flat list of all the layers. I know that in the cartoon below they are not in alphabetical order.)
- by protocol (similar to current design but also include the layers underneath each protocol. Obviously there would be duplicates.)
- by geometry type (point, line and polygon)

Any more than three options and probably switch to dropdown instead of radio buttons.

![PXL_20221025_035755916](https://user-images.githubusercontent.com/8645379/197679710-b36fd10b-3237-4720-893e-a2656fe73fe2.jpeg)

Thoughts @joewheaton  and @nick4rivers

**Comment by joewheaton** [comment]
## Clarification
Hey @philipbaileynar, thanks for this.  To clarify, it is not that I don't like "Protocols", but I don't like how we're teaching or managing the user's expectations of them yet. We need to find a way to convey that really what the  `New DCE` Form or the `Edit DCE Properties` form is controlling is which custom layers get added to your DCE in your QRiS project. Right now, that is obscured because no one knows what a Protocol is, and the entry that you put in the QRiS tree is disconnected from what gets displayed and added way over on the TOC Layers tree. 

I do think there is value for power users (once they understand what a "Protocol is" in providing a "Choose Layers by Protocol" option because it will be a shorter list to choose from. We just jump from All to Nothing to quickly to nothing here. 

## Feedback on your Proposal
You proposed:

> Here's my suggestion for how we could organize them:
> 
> - alphabetical (essentially a flat list of all the layers. I know that in the cartoon below they are not in alphabetical order.)
> - by protocol (similar to current design but also include the layers underneath each protocol. Obviously there would be duplicates.)
> - by geometry type (point, line and polygon)
> 

I don't dislike this... I just think it needs "Methods" too. 

I don't think we should allow Protocols or Methods without them being defined in MonitorinfMethods.org.  Remember, a protocol is a collection of methods. A method is the more granular logical level to build a collection of layers associated with something.  The combination of alphabetical, methodological, and protocol and geometry type is good. I think we also need generic points, polylines, polygons, that can represent anything the user decides.

**Comment by joewheaton** [comment]
Thanks for this @philipbaileynar (both redesign and little video). Comments in chronological order of your video:
- Thanks for adding LTPBR Designs & As-Built menu items. I could go either way on your comment about the sub-menu versus keeping menu flat. I suspect that you have a strong point right now (i.e. when there are not that many menu items keep 'em flat), but I predict that over time if this right click context menu goes, what we have may be desirable. 
- I like the isolation of Layers on to their own tab. I am torn whether Layers or 'Basic Properties' should come first. I think Layers are going to be the more common thing to fiddle with. However, to the extent that 'Basic Properties' are the 'When' and 'What' they are arguably more fundamental. 
- I like initialization as "Hierarchical"
- I like how Alphabetical displays. 
- I like the functionality of ` [x] Show only Active Layers`, but "Active" is too close to geomorphic terminology and also to loaded of a term. I would suggest "Used" or "Initiated" or something. It might also be helpful in one of these trees to know the difference between empty, initiated layers that are unpopulated, vs. those that are populated with actual features. 

One flaw that I do not like is that in your "Hierarchical" system (as proposed), is you seem to assume that all methods have to exist in one or more Protocols. This is false. I think we will have a bunch of methods that are not actually collected into a protocol. I also don't like that it obscures the difference between Methods and Protocols. I think the behavior you have created is close to what we would like (maybe with show only active layers on) in the DCE part of the QRiS tree. I think that the tree control is useful, but your obscuring some concepts for new users. Some thoughts:
- You can keep your tree as the `Hierarchical Protocol` View and add new view of just `Hierarchical Methods` view to make it clearer. 
- You can keep your tree and add a container for "Methods not Associated with a Protocol"
- You can add these ideas above and keep what you have, but make the idea of `Layers Included` as its own thing with the `>` vs `>>` add all type control where the right hand list is always your layers included and you see more explicitly that this is the thing you are actually controlling and doing on this form and there are different ways to do this.

Great progress.

**Comment by philipbaileynar** [comment]
I do not like the two control concept. I'm just trying to decide how much of a stubborn cry baby I want to be about it 🤣

**Comment by philipbaileynar** [comment]
Before I make any changes I want to figure out what should be shown in the project tree and map ToC?  Should protocols and or methods appear in either of these locations?

Option 1 - Methods and Layers

```
- Project
    - Data Capture Events
        - My DCE
             - Method A
                 - Layer 1
                 - Layer 2
             - Method B
                 - Layer 2
                 - Layer 7
```

Option 2 - Just Layers

```
- Project
    - Data Capture Events
        - My DCE
             - Layer 1
             - Layer 2
             - Layer 7
```

Option 3 - Protocols, Methods and Layers (not shown because I suspect it's the lowest priority given Joe's comments that lots of methods will not have a protocol.

And before you say "both".... This work is blocking project upload/download round-trip. So let's pick one and we can implement multiple layouts layer.

**Comment by joewheaton** [comment]
Option 1 please.

**Comment by philipbaileynar** [comment]
I just realized that option 1 doesn't really work....

We keep track of which layers are included in an event, not the methods. So we can't show the methods in the project tree or map ToC.

I have still not agreed to implement @joewheaton right hand "layers in use" list, but if we do go down that route, it's another level of separation between the layers and methods. In that list view, which method does a layer belong to? Does a layer in that list belong to one method, or all the methods that the user clicked on to add it?

**Comment by philipbaileynar** [comment]
Done!
