### ISSUE TITLE
DCE Dates and Fields

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#169]
# Dates

Enhance the date specification for data capture events (DCE) on the Basic Properties tab to allow for the following. As the user toggles the radio buttons the child controls should enable/disable accordingly.

- "Single Point in Time" (radio button)
    - single `frm_date_picker` control
- "Date Range" (radio button)
    - the existing start and end date controls.

# Representation

Add a new Dropdown control on the Basic Properties tab with the label "DCE Represents". The values of the dropdown should come from a new lookup table. The values are:

- Current
- Historic
- Future

Default new DCE to "Current".

<img width="495" alt="Screenshot 2022-12-21 at 4 29 07 PM" src="https://user-images.githubusercontent.com/8645379/209029139-fd67666e-d830-4453-b93a-dc2c09457657.png">

**Comment by KellyMWhitehead** [comment]
Date widget adjusted for single and range of dates

Representation added, including lookup table and event schema change to store the representation.

**Comment by joewheaton** [comment]
So the DCE or data capture event is about creating a container for data capture tied to a specific events. This tab is currently labeled `Basic Properties`, which to me doesn't really convey that this is really about the snapshot in time. @philipbaileynar I'm thinking that we might want to rename this tab `Event Properties` because "event" does actually convey time. Thoughts?

I am also thinking that it may be more logical to have this as the first tab (i.e. "when" are you capturing data for? ), and then get into what. I have an old ticket that conveys, this but what if _this_ was the first tab and it was labeled simply `When?` or `When is DCE?` or `When is Event?` and the tab that is `Layers` changes to `What? (Layers)`.

**Comment by philipbaileynar** [comment]
Responding to Joe's renaming request... Obviously changing labels is easy. However, I will point out that the "Basic Properties" tab is where we put any additional controls for special DCE types, such as designs. So this tab is kind of a catch all for several fields. So renaming it just to convey time is not perfectly applicable. (Note when showing design properties that the layers tab is disabled because the layers for design are prescribed, and therefore the basic properties tab does become the first tab.)

# Basic Properties for regular DCE

<img width="612" alt="Screenshot 2023-02-27 at 1 32 02 PM" src="https://user-images.githubusercontent.com/8645379/221690334-5e6e4040-ead5-4f98-9b03-acf7d1479643.png">

# Basica Properties for Design DCE

<img width="612" alt="Screenshot 2023-02-27 at 1 34 18 PM" src="https://user-images.githubusercontent.com/8645379/221690764-c3c5def4-b08e-40d4-9e1a-00a2213b3b5a.png">

**Comment by philipbaileynar** [comment]
I am going to close this issue. There's still Joe's outstanding request to rename the tabs (When, Where etc). I'm not a big fan of this language and also there's the important issue that I raised whereby the Basic Properties tab is reused for Designs. This kinda trumps everything until we come up with an alternative.

Let's get some reps on using DCE and reopen this issue if we can't live with the current naming.
