### ISSUE TITLE
Fail to commit changes in design edits with import

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#179]
In attempting to migrate existing designs, changes are failing to save in an edit session. I can copy features from an old design and paste in a new project. It seems to be symbolizing things correctly on import but wont save the changes when ending the editing session.
![QRiS import](https://user-images.githubusercontent.com/97305413/221054780-b21addf8-a9ba-40d3-bef1-961e6817c727.png)
Everything looks good coming in.
![QRiS error](https://user-images.githubusercontent.com/97305413/221054821-e0514d4c-f93a-40ef-b5e1-89ead70ac19e.png)
Error I'm getting when trying to save edits.

**Comment by philipbaileynar** [comment]
@Jdgilby can you explain, step by step, precisely how you are copying and pasting features? Are you using CTRL+C and CTROL+V etc? Perhaps you could record a video?

I have a sense of what is going on here... QRiS associates each structure geometry with the parent data capture event (DCE). When you just cut and paste geometries it is unable to create the feature because it doesn't know what the parent database ID of the DCE is. (This is frustrating because the layer you are pasting into is already filtered to the correct DCE, so I'm disappointed that QGIS can't figure this out).

@KellyMWhitehead can you explore setting "default values" for the foreign keys? I think @nick4rivers had some code to do this!?

**Comment by Jdgilby** [comment]
@philipbaileynar Ya I pulled in layers from a past design(I couldn't directly load an old design into the newest version of QRiS) and started editing the layer I wanted to copy in. I selected features and then started an editing session in the new design/data capture event (I tried both ways) for the same feature class and copied them in. They show up like the picture above but won't save the changes when finishing the editing session. 

Joe wanted to test functionality of copying in old designs and Nick figured this would happen with all the database relationships and attributes.

**Comment by philipbaileynar** [comment]
You are trying to do the right thing. QRiS must support this workflow. @KellyMWhitehead is investigating as I write. This is our topmost QRiS priority right now. We will have a fix ASAP.

**Comment by KellyMWhitehead** [comment]
@Jdgilby 

The issue should be fixed in this [new release](https://github.com/Riverscapes/QRiS/releases/tag/0.1.13-alpha).

**Comment by philipbaileynar** [comment]
@Jdgilby please re-test and close this issue if fixed, or provide more information if there's still a problem.

You should not have to create a new QRiS project to get this fix. Simply update your QRiS software installation.

Thanks @KellyMWhitehead

**Comment by Jdgilby** [comment]
@philipbaileynar The saving issue was fixed, however, now the type of structure has changed when pasted in. Bank Attached PALS became BDA Large, Channel Spanning PAL became BDA Postless, and Mid Channel PAL became BDA Small. This was not happening before when I posted this issue.
