### ISSUE TITLE
Cross Sections Dockable Window Enhancements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#241]
- [x] Add a select button beside the profile control (similar to raster slider and proposed change for cross sections)
- [x] Spacing and Extension have the units as part of the label. Centerline tool has the units within the textbox control. Please standardize.
- [x] Default spacing to 50m.
- [x] Change `Extension` to `Length` and have the user specify the total length of the transects.
- [x] Move reset button to same horizontal row as the other to buttons.
- [x] Reduce size of Help button to be similar to the other buttons.

**Comment by KellyMWhitehead** [comment]
Let me know if you like this aesthetic. It is similar to the centerline tool, with a groupbox instead of tabs.


![Image](https://github.com/Riverscapes/QRiS/assets/10746997/4eabfa60-6a00-4f51-8075-5c74e3f5eb15)

Reset button is grouped with the inputs, help is below and to the left, and the 'functional' buttons are to the left moving down in order of operation.

**Comment by KellyMWhitehead** [comment]
@philipbaileynar Cross section tool starts at the first vertex of the centerline. Seems like this is likely to cause the small slivers when we create the sampling frames. Do we want to drop this transect? Provide the user an option to keep/drop the first transect?



![Image](https://github.com/Riverscapes/QRiS/assets/10746997/a9e7acb6-6e8a-444d-800d-144500114f26)

**Comment by philipbaileynar** [comment]
Yes. I think the first logical transect is at the spacing distance along the centerline. 

It's unrealistic that we will get this 100% correct. Users will have to edit polygons and lines. But I think this decision helps.
