### ISSUE TITLE
Watershed catchments disappear when zoomed in or when panning

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#253]
[Heres ](https://youtu.be/OtYiCEhSWUc)a quick video

**Comment by KellyMWhitehead** [comment]
Took a bit of sleuthing, but I found that the issue was an invalid geometry (self-intersecting polygon). For whatever reason, the polygon will only draw if the bad section of geometry is in the map extent. 

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/7dcb1a0d-6d93-427f-ab2c-f38f19bad00c)

I have made a fix to the catchments tool that will fix invalid geometries moving forward, but does not fix existing data. You will either have to repair any bad geometries, or just as easy, create a new catchment with the updated tool.

Fix is for version 0.2.5
