### ISSUE TITLE
Bespoke Metadata Columns

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#277]
During the import of external feature classes we allow the user to keep attributes and store them in the feature metadata. These metadata values are obviously bespoke and unique to the feature class that you imported. (i.e. not all data capture events will have these metadata JSON keys.)

What would it take to keep a list of these imported attribute names and then destructure them into spatial view columns for the individual DCE layer?

**Comment by KellyMWhitehead** [comment]
I reconfigured the layer manager that handles the virtual metadata field creation:
1) "Required" fields (i.e. those specified in the qris layer definition) are generated first. These will get a metadata widget in the attribute form that will allow for edits, lookups, etc.
2) any other metadata keys will get added as fields with a 'best guess' as to the field type (this was the behavior in a previous release). We can choose if we want to add a prefix or something to denote the 'custom' nature of these attributes. As of now, the would need to be treated as 'read-only' since the metadata widget needs the 'field' defined ahead of time.

**Comment by KellyMWhitehead** [comment]
Reconfigured the attributes in the metadata field for dce layers. Required attributes are stored under the json key "attributes" and all other imported fields are under the key "metadata". The same rules for read-only still apply.
