### ISSUE TITLE
Basemaps Icons

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#288]
![image](https://github.com/Riverscapes/QRiS/assets/9723905/a792ef74-811c-4a9a-8e9b-fd4f58d98049)

But maybe @philipbaileynar this happens automatically when you guys release the update to Q-RV Riverscapes Viewer as this is actually just pointing to that that code?

**Comment by KellyMWhitehead** [comment]
Basemaps are managed in the Riverscapes Viewer (QRIS pulls them in from there).  Normally this would update when the user updated QRAVE, but since we renamed the plugin, I will need to change QRIS to point to the new Riverscapes Viewer plugin name. Easy change for the next QRIS version early next week.

**Comment by KellyMWhitehead** [comment]
Ready to go for 0.3.6

**Comment by joewheaton** [comment]
Fixed with 0.3.6
