### ISSUE TITLE
Implement LTPBR Metrics

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#310]
Please identify the low hanging fruit metrics in this spreadsheet and implement in the existing software.

Enumerate those that are either hard or need more clarification for discussion with @joewheaton 

https://docs.google.com/spreadsheets/d/1HiQa90HpYAx-yqDyxyF3MHViQ0egF-la8mrQtfF7KB4/edit?usp=sharing

**Comment by joewheaton** [comment]
## Conversation NOTES
> We can generate metrics (feature counts, lengths, areas, area proportions, gradient, and sinuosity) based on layer(s), with or without attribute filters. Some metrics will need valley bottom area, valley bottom centerline, and/or DEM.
> 
> Here is my current understanding of metric the metric needs and tasks:
> 
> * [ ]  **Proportion of Active Valley Bottom**
>   We need to add as Valley bottom as a context layer type, an need to provide the user with a way to select/associate with a DCE and/or Analysis

Need **FOR ALL** : 
- Valley Bottom Area as total sample frame Area
- 
Layer: Active / Inactive
Attribute: Type
Category Used: "Inactive" 
Calculated by
- 100- (Inactive Extent Area / Valley Bottom Area)*100
- OR - Active Extent / Valley Bottom Area * 100


Issue: 
- Relies on user mapping "Active Extent" as combination of Active Channel and Active Floodplain
- Future might be asking to draw "Inactive"


> * [ ]  **Natural Flow Regime Present**
>   Not sure ??

This is not a calculation from digitized data. This is an assessment. (Manual entry)
We need to provide with LTPBR V 2: the choices.

Future Feature Request
- Copy answer to all other sample frames
- Copy answer to all other sample frames of same levelpath 


> The following will need VB centerline. Same as VB polygon, user to select from profiles. This will be used to normalize by km
> 
Need **FOR ALL** : 
- Valley Bottom Area as total sample frame Area
- Valley Bottom CL, length for each sample frame 

Feature
- Right click on CL and segment by sample frame 
- Later option, add CL to map with symbology (right click from that row in calculations table)

> * [ ]  **Jam Density (LWD jams / km)**
>   Sum of Count per mask (structure_point, structure_lines, structure_complexes with appropriate filters)

Yes. The count is tricky here. You have to look at all three to get a total. For structure_point

Polylines and Polygons, what do we do? 
Pro-rate based on proportion of line lenth or polygon area. For count = 1, round to nearest integer (shorter one goes to zero, larger to 1). 

>   How will we count lines/areas that cross sample frames? Maybe double counting is ok as we are normalizing by km?

- This is actually riverscape jam density, it is therefore LWD jams/ unit length of riverscape) 

Can of worms:
- Units
- Always store SI units


> * [ ]  **Jam Capacity (LWD jams / km)**
>   ??

This is same as above. Just using type: Jam instead of type Dam

> * [ ]  **Beaver Dam Density (beaver dams / km)**
>   Sum of Count per mask (structure_point, structure_lines, structure_complexes with appropriate filters)

This is same as above. Just using type: Dam instead of type Jam

> * [ ]  **Beaver Dam Capacity (beaver dams / km)**
>   ??

This is a BRAT assessment. 

> * [ ]  **Number of Active Channels**
>   Count number of centerlines (filtered by Primary and non primary features) per mask
> * [ ]  **Number of Active Channels**
>   Duplicate in source table?
> * [ ]  **Diffluence Density (# / km)**
>   Count of features in channel_junctions filtered by Type = Diffluence
> * [ ]  **Confluence Density (# / km)**
>   Count of features in channel_junctions filtered by Type = Confluence
> * [ ]  **Floodplain Channel Head Density (# / km)**
>   Count of features in channel_junctions filtered by Type = Channel Head
> * [ ]  **Pool Desnity (# / km)**
>   count of  geomorphic_units filter by "Type2 Tier" = "Bowl"
> * [ ]  **Mid Channel Bar Density (# / km)**
>   count of geomorphic_units filter by "Type2 Tier" = "Mound"
> * [ ]  **Riffle Density ( # / km)**
>   count of geomorphic_units filter by "Type2 Tier" = "Saddle"?
> 
> Not sure about these:
> 
> * [ ]  **VB Mesic Resources (% of years mesic)** ??
> * [ ]  **VB Mesic Resource Resilience (0 to 1**) ??
> * [ ]  **Complexity Resilience (0 to 1)** ??
> 
> Areas (filter by type) per mask area
> 
> * [ ]  **% Inundated @ Baseflow**
>   area of active channel (bankfull) or other?/ mask area
> * [ ]  **% Inundated @ Typical Flood**
>   area of active extent or other / mask area
> * [ ]  **Free-Flowing (area of inundation**
>   area of inundation (filter by Extent Type = "Free Flowing")/ mask area
> * [ ]  **Backwater / Ponded**
>   area of inundation (filter by Extent Type = "Ponded")/ mask area
> * [ ]  **Overflow (area of inundation** (
>   area of inundation (filter by Extent Type = "Overflow")/ mask area)
> * [ ]  **Check ∑ to 100%**
>   Needed?
> 
> Areas (filter CEM? by type) per mask area
> 
> * [ ]  **Stage 0 - Anastamsoing**
> * [ ]  **Stage 1 - Single Thread**
> * [ ]  **Stage 2 to 3 - Incised**
> * [ ]  **Stage 4 - Degradation & Widening**
> * [ ]  **Stage 5 - Aggradation & Widening**
> * [ ]  **Stage 6 - Quasi-Eqilibirum**
> * [ ]  **Stage 7 - Laterally Active**
> * [ ]  **Stage 8 - Anastamosing**
> * [ ]  **Check ∑ to 100%**
> 
> ??
> 
> * [ ]  **Day of Year Flows Dry Up**
> * [ ]  **Fish Density (fish / 100 m)**

**Comment by Jdgilby** [comment]
@KellyMWhitehead Heres the low hanging fruit metrics. 
[Metrics.zip](https://github.com/user-attachments/files/15595687/Metrics.zip)

**Comment by Jdgilby** [comment]
@KellyMWhitehead How are we dealing with double counting in instances like this? 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/97787949-df93-45ef-9160-5a74c78a02b5)
This would be Jam Density metric. I have both points and areas digitized. SHould we have structural elements areas only allowed to calculate an area metric and not be involved in count?

**Comment by KellyMWhitehead** [comment]
Currently we do not do any exclusion or checking between the layers (other than pro-rating area or length between sample frames).

Questions:
1) Is this an accidental occurrence (that needs to be prevented) or are there valid reasons for this to exist.
2) If this is valid, is double counting permitted, desired, or needs to be prevented?

Some options:
1) do nothing, train and/or update documentation to direct the user to the desired outcome (easiest to implement, however no protections)
2) Set up checking or prevent user from digitizing erroneous features (could be difficult to set up/specify in layers, but no changes to metrics are required).
3) Adjust metric calculation to not double count overlapping features in these instances. What is the priority between layers? Do we ignore points  or lines that fall within structure areas? What about proportion of line within an area? This might be less error prone than option 2, but we need to be clear about priority order. This also needs to be carefully implemented as this could balloon processing time checking between all of the various layers used in the metric.
4) other ideas?

**Comment by Jdgilby** [comment]
@KellyMWhitehead I would say it is not an accidental occurrence. Structure count doesn't paint the whole picture since in some cases structure count goes down but area goes up. So you might digitize both in a project. Unlikely though that you would only do jam area and get a count off that since smaller jams are harder to digitize as an area, so a point becomes useful there. 

Im leaning toward option 3, however, I get how that might create some complicated issues. If its not reasonable, I like option 1 with some sort of warning/documentation that is obvious.

**Comment by philipbaileynar** [comment]
My $0.02 worth...

We should NOT make any attempt to combine the two layers into a single metric. We can calculate density from the points, and we can calculate density from a polygon with a count attribute. Then the decision becomes:

1. One metric where we automatically prioritize one of the calculations I described if both layers exist.
2. Two metrics, one for each layer, with a name that distinquishes them ("Jam Density" and "Jam Density Aerial" etc)

We must avoid user interface input where the user picks which layer to use for the metric.

**Comment by Jdgilby** [comment]
@KellyMWhitehead @joewheaton @philipbaileynar 

Status update, just finished these metrics. 

[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count
[x] Active Channel Count

**Comment by joewheaton** [comment]
@Jdgilby and @KellyMWhitehead where are we at on this. I think it should be closed in favor of more specific smaller issues.

**Comment by Jdgilby** [comment]
@joewheaton I agree I'm closing it.
