### ISSUE TITLE
RAP API Request

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#344]
We want to prove the concept of reaching out into external APIs to bring metrics into QRiS. The first of these is the [Rangeland Analysis Platform](https://rangelands.app).

Goal: Prove that we can take an AOI or sample frame polygon, convert it to GeoJSON and then use it to retrieve the "Riparian Resilience Index" metric and store it in the QRiS database. Apparently RAP has an API that should make this possible.

Dig in. See what you find. Report back here.

QuestionS:

- What other metrics are possible?

FWIW... might be worth developing this as a standalone Python script first, just to speed up dev cycles. Then integrate into QRiS once working.

**Comment by KellyMWhitehead** [comment]
I don't see a stand-alone api. There are couple Google Earth Engine scripts, a web tile url (though it seems to limit how far we can zoom in) and a folder of very large rasters.

**Comment by KellyMWhitehead** [comment]
The research phase of the climate engine api is complete:
- We have an API key for QRiS and a strategy to deploy it.
- We have made several successful data requests through the api.
- A test form and initial climate engine functions have been developed (currently on a feature branch).

All of this to day we are ready to start incorporating this data into qris, as metrics or otherwise.
