### ISSUE TITLE
Climate Engine Explorer - Polygons Not Showing up

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#368]
1. Create new project
2. Create new "manual" empty sample frame
3. Digitize three polygons
4. Click pencil to stop editing and choose to "Save Edits"
5. Click Explorer Climate Engine
6. Panel only shows one feature
7. 
<img width="1421" alt="Screenshot 2024-05-07 at 3 01 44 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/cfdc5afb-5a7f-40ca-a1ba-312369288229">

**Comment by philipbaileynar** [comment]
Here's the project that's exhibiting this behaviour.

[testce.zip](https://github.com/Riverscapes/QRiS/files/15241777/testce.zip)

**Comment by KellyMWhitehead** [comment]
This is due to null values for "display_label", which is used to populate the checkbox list.

@philipbaileynar what should our strategy be here:
1) enforce non-null display_label field
2) use FID (or other field) instead of display_label field
3) hybrid (use display_label if not null, else FID)
4) other?

**Comment by philipbaileynar** [comment]
number 3. Use display label if it exists. Else "Feature XX" where XX is the feautre ID

**Comment by KellyMWhitehead** [comment]
Applied option 3.
