### ISSUE TITLE
Watershed Cachements/StreamStats Error for 0.3.17

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#378]
When I try running the StreamStats tool on 0.3.17, I get this issue. 

![Streatstats Error Not Running](https://github.com/Riverscapes/QRiS/assets/150490067/472ce3ce-7b15-48c2-9b28-58d6b2bd4849)

**Comment by KellyMWhitehead** [comment]
Fixed for 0.3.20

Removed the openstreetmap reverse geocoding api call since it looks like we were reaching some usage threshold.

QRiS is now deployed with a simplified state boundary geopackage to determine the US location of the pour point. I also added the state status for the stream stats and some logic to inform the user of any limitations in that state.
