### ISSUE TITLE
Some sort of description of status in Analysis

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#386]
The orange and blue dots need some sort of description. Not intuitive at all as is. A legend maybe, or a different way of displaying with heading. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/d9c04928-41f4-4edb-8d03-ce30ad0f685b)

**Comment by KellyMWhitehead** [comment]
I have added Tool Tips (hover over the status icons, shown in blue) and a button that links to the relevant section in the help (red):

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/310ba6a6-0561-4180-a711-e993be0dd7ed)

@jtgilbert will this meet the need or is more needed? (I know the tool tips aren't always intuitive)

@MattReimer I am having some trouble with linking to headings within a help doc. For example: https://qris.riverscapes.net/software-help/analyses/#metric-table goes to the page, but not the heading.

@philipbaileynar anything else to add here?

**Comment by philipbaileynar** [comment]
Yes, there's something squiffy about the in-page anchors. The "on this page" links are not working either.

----

I'm curious about @Jdgilby satisfaction with the status tool tips.

----

The three other bits of information that I think are needed here are:

1. Hyperlinks to the specific documentation for each metric (I know we have them on edit modal form, but I think they are necessary here too. Maybe use the metric names as hyperlink?
1. Information about which layers are necessary for a metric to be auto calculated. I think it will reduce frustration when metrics don't auto calculate because of missing information. Flipping this on its head, this list of layers can be motivation for encouraging users to go to the effort to digitize certain layers.
1. Error warnings. I think this warrants a separate column to the right of Status, perhaps with the heading "Info". Kelly could you generate a nice error icon in the same color scheme as the rest of our new icons? This icon would only appear when auto calculation fails for a metric. Clicking the error icon either:
    1. shows a new modal with list of error messages (including missing layers).
    2. opens and brings focus to the correct QGIS message dockable window where these messages are posted.

![image](https://github.com/Riverscapes/QRiS/assets/8645379/1cf6fed8-e08d-47c0-9534-acde44b07519)

**Comment by Jdgilby** [comment]
@KellyMWhitehead @philipbaileynar Ill check it out on the next release. This hopefully does the trick but I know users complaints with analysis was that certain components aren't that intuitive. This should definitely help.
