### ISSUE TITLE
Add a Planning node under DCEs

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#391]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/5462532e-8fef-4737-b943-844f310d86d7)

Add a drop down menu here to specify a 'Regular DCE' or a 'Planning DCE'.
If planning is selected a new node populates in Data Capture Event Nodes called 'Planning Event' as a container for all potential future planning DCES. 

So Plugin tree would appear as follows.

Data Capture Event
>Planning Event (New Node)
>>Planning 2023....(populates here when planning event specified in properties)

Design 1...
As Built 1.....
DCE 2023....

Brings up a organization question..... Should we add nodes for designs, as builts, and regular DCEs for organization? Or leave as is.

@joewheaton Will you review and make sure this what you visioned with this?

**Comment by philipbaileynar** [comment]
@Jdgilby instead of the dropdown you proposed, can we add planning DCE to the existing list of DCE types under the LTPBR menu? Essentially "Planning DCE" would be in the same vain as design and as built... Note that this gives us the option of having custom attributes for planning DCE (as well as defining the default layers).

<img width="452" alt="Screenshot 2024-05-28 at 11 47 38 AM" src="https://github.com/Riverscapes/QRiS/assets/8645379/0f7b76a0-d8a9-4e5a-a972-3d10b760ebe9">


# Tree Representation

My recommendation on the project tree is that we add an "Organize by..." right click to the "Data Capture Events" node with two self explanatory sub menu items:

- Organize by date/time
- Organize by type

I think there is merit to seeing the DCE organized chronologically so that the user can see the timeline of events. My proposal allows users to switch back and forth.

**Comment by Jdgilby** [comment]
@philipbaileynar I think what you suggested makes more sense, and the form should more or less mimic the normal DCE form. And I agree a layers attributes might be different. This issue goes along with #403 and #404. This whole concept gets a little murky but I think its all important to find a way to tie it together in a way that makes sense.

**Comment by KellyMWhitehead** [comment]
Added in 0.3.23. 

@Jdgilby please verify these layers when you get a chance.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Ya that looks good.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Hey I just tried to create a planning event and there are no options for layers.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/f8061217-616f-45d2-985d-241da1d6a925)

**Comment by KellyMWhitehead** [comment]
@Jdgilby y, I realized I forgot to turn those layers on in that release. They will be ready to go in 0.3.24, which I will try to get out today or tomorrow.

**Comment by Jdgilby** [comment]
@joewheaton Can you comment on proposed changes

**Comment by joewheaton** [comment]
This issue I am closing as the first version of this exists. I will make a new ticket for next iteration.
