### ISSUE TITLE
RiverscapesStudio projects

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#405]
Business logic has been stubbed out on[ RiverscapesXML](https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/V2/RiverscapesStudio.xml) and is ready to be expanded/updated as needed.

1) I think the symbology will need to be copied from QRiS symbology folder since this is a new project type.

2) Older exported projects will need the project type changed from "QRiS" to "RiverscapesStudio".

Let me know if you have any questions or issues.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Do I need a Qris export to open and edit business logic and view it in riverscapes viewer?

**Comment by Jdgilby** [comment]
@KellyMWhitehead Can you send me and a zipped up project export, I still cant get through export successfully.

**Comment by KellyMWhitehead** [comment]
Here is an export of willow springs, should have a good variety of datasets to test out [new_export.zip](https://github.com/Riverscapes/QRiS/files/15395998/new_export.zip)

**Comment by Jdgilby** [comment]
@KellyMWhitehead It appears we have an issue with symbology. Proper symbologies get displayed in the layer tree when opening a project. However, everything is displayed as the catch all symbology.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/83fce3b8-c9a0-418a-9a36-8615ef9e81b1)
It appears to be because the metadata is not populating the attribute fields such as Structure Type, so nothing gets symbolized.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/966d9bc4-70b3-4a68-97d5-d179b3a7066c)
Heres the Fields tab in the viewer vs in QRiS
![image](https://github.com/Riverscapes/QRiS/assets/97305413/ffce0639-b4f0-4aa5-ab91-342ef883dd6a)
![image](https://github.com/Riverscapes/QRiS/assets/97305413/9e50b215-1252-438f-939e-3fe94f35ef90)
Testing confirmed this is the issue. 

Is there a way to export with the same metadata functionality as QRiS project has or is it better to create different RiverscapesViewer symbologies that are based on the metadata field instead of the field they are symbolized on in QRiS?

**Comment by KellyMWhitehead** [comment]
@Jdgilby I think I've fixed the issue. Please try this project and let me know

[symbology_fix.zip](https://github.com/Riverscapes/QRiS/files/15425079/symbology_fix.zip)

**Comment by Jdgilby** [comment]
@KellyMWhitehead That looks like it worked
