### ISSUE TITLE
Migration and machine_name error Mac OSX

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#432]
Hey, after installing newest version of QRiS and the RV I get python errors whenever I try to OPEN or CREATE new projects. This is just on my Mac but works fine on Windows machine. Uninstalled and reinstalled plugins but still no luck.

![Screen Shot 2024-06-29 at 9 15 38 AM](https://github.com/Riverscapes/QRiS/assets/34071692/7387a310-8b54-40a5-b771-7a3386927995)
![Screen Shot 2024-06-29 at 9 13 55 AM](https://github.com/Riverscapes/QRiS/assets/34071692/f03f33ea-4fb8-47d3-bb6c-84f95e3e6162)
![Screen Shot 2024-06-29 at 9 13 44 AM](https://github.com/Riverscapes/QRiS/assets/34071692/7501b7a2-74c3-4390-b783-b968e5316bc2)

**Comment by KellyMWhitehead** [comment]
@nick4rivers the test version I sent you should fix this for projects moving forward, however, some previous projects might have had the migrations loaded in the wrong order. If you still see these types of errors on an existing project, I will likely need to make a repair to the project on my end.

Otherwise, this fix will be released in version 0.3.26.
