### ISSUE TITLE
Climate Engine Explorer Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#515]
# Easy

- Rename "Climate Engine" button to be "About Climate Engine" on the "Climate Engine Metrics" tab.
- Move the "About Climate Engine" button to the right of the Help button. It's unclear that this button is a lower priority than the "Download Metrics" button. The latter is essential to the workflow of this tool, but the former is simply a link to their website.
- Download Metrics Form
    - Fix vertical alignment of the "Sample Frames" label with the dropdown. Are you using a QFormLayout?
    - Ensure that the features are pre-selected that were selected back on the dockable window. (I selected two features on the dockable window, but they were not then selected on the Download dialog when I opened it.
    - Make the Dialog 200 pixels taller by default. Feels a bit crowded and I want to see more variables.
    - Put a group box around the date range controls. (The "Date Range" label can stay outside the group box because you're using a QFormLayout. But put the dropdown and two date controls inside the group box.)
    - Rename the "Get Timeseries" button to be "Download Metrics" (more consistent with form title and the button clicked to launch the form).
    - I wonder if we want a checkbox with label "Keep Window Open After Download". The default would be for this to be checked and for the dialog to close and return to dockable window. I think that this is the more common workflow. Users who want to perform multiple downloads (using different timeframes) could uncheck the checkbox to retain the existing functionality.
- Explorer and Chart    
    - When the dialog closes, pre-select one dataset in the Climate Engine Metrics tab to help the user out. It's disconcerting that currently nothing happens when the dialog closes.
    - Change x axis label to "Time" instead of "Date.
    - Change y axis to name of variable with units in parentheses.
    - Apply light grey grid to chart (ask GPT...)
    - Apply minor tick marks to both axes.
    - Remove light grey border around legend.

# Sure Would be Nice

- Any chance that we can make the download an asynchronous  QTask, and also the user to continue using the tool while the download proceeds in the background?
- Apply a group box around the "Date Range" and another for "X-axis Represents" to try to convey grouping. Alternatively, I wonder if putting the X Axis underneath might be clearer, albeit consuming valuable vertical space.
- Are there more variables that we can grab from the API for the metadata? Full description? Full units string? Separate URL for each dataset or variable?

Lower Priority (if easy)

- When there's only one sample frame in a project, make it the default selection. (I know this is hard because the dock window exists before it's actually shown and so updating this combo might be hard. Only tackle if easy.)
- Weird that MatPlotLib chart axes exist before there's any data. Consider having an initial widget with QLabel and instructions for using the tool. Then switch this out for MatPlotLib chart widget once all the conditions are met for showing data.

**Comment by KellyMWhitehead** [comment]
Complete for 1.0.2:

Explorer Dockable Window
- [x] Rename "Climate Engine" button to be "About Climate Engine" on the "Climate Engine Metrics" tab.
- [x] Move the "About Climate Engine" button to the right of the Help button.
Download Metrics Form
- [x] Fix vertical alignment of the "Sample Frames" label with the dropdown.
- [x] Ensure that the features are pre-selected that were selected back on the dockable window
- [x] Make the Dialog 200 pixels taller by default
- [x] Put a ~~group box~~ QFrame with border around the date range controls
- [x] Rename the "Get Timeseries" button to be "Download Metrics"
- [x] Added checkbox with label "~~Keep~~ Close Window Open After Download". The default would be for this to be checked and for the dialog to close and return to dockable window.
- [x] Change x axis label to "Time" instead of "Date.
- [x] Change y axis to name of variable with units in parentheses.
- [x] Apply light grey grid to chart
- [x] Apply minor tick marks to both axes.
- [x] Remove light grey border around legend.

- [x] When there's only one sample frame in a project, make it the default selection. (I know this is hard because the dock window exists before it's actually shown and so updating this combo might be hard. Only tackle if easy.) This was easy - made the change where the SampleFrameWidget initializes.
- [x] Weird that MatPlotLib chart axes exist before there's any data. Consider having an initial widget with QLabel and instructions for using the tool. Then switch this out for MatPlotLib chart widget once all the conditions are met for showing data.

Remaining Tasks:
- [ ] When the dialog closes, pre-select one dataset in the Climate Engine Metrics tab to help the user out. It's disconcerting that currently nothing happens when the dialog closes.
- [ ] Any chance that we can make the download an asynchronous QTask, and also the user to continue using the tool while the download proceeds in the background?
- [ ] Apply a group box around the "Date Range" and another for "X-axis Represents" to try to convey grouping. Alternatively, I wonder if putting the X Axis underneath might be clearer, albeit consuming valuable vertical space.
- [ ] Are there more variables that we can grab from the API for the metadata? Full description? Full units string? Separate URL for each dataset or variable? _I will check if there are any more. Initially we had to ask for the description to be exposed in the api in addition to the variable id, so unless they added more, this is probably it for now._

**Comment by KellyMWhitehead** [comment]
Tasks for this ticket were added for version 1.0.2

Remaining tasks are moved to new issue #517 and #518

**Comment by KellyMWhitehead** [comment]
Updated UI:
![image](https://github.com/user-attachments/assets/b50bb219-3505-445f-aae7-d6bc9d9b1d92)

Download form:
![image](https://github.com/user-attachments/assets/963cc98d-5bbb-4075-b610-b95dcd7b8d2c)
